version: "3"
services:
  wyl:
    image: aceberg/watchyourlan
    network_mode: "host"        
    restart: unless-stopped
    volumes:
    - ~/.dockerdata/wyl:/data/WatchYourLAN
    environment:
      TZ: Europe/London                 # required: needs your TZ for correct time
      IFACES: "enp4s0 wlxf4ec3892dd51"  # required: 1 or more interface - get a list of network interfaces by running: ip link show
      HOST: "0.0.0.0"                   # optional, default: 0.0.0.0
      PORT: "8840"                      # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 120
      SHOUTRRR_URL: ""                  # optional, set url to notify - check https://containrrr.dev/shoutrrr/v0.8/services/pushover/ for Pushover, Discord etc. URL
      THEME: "sand"                     # optional Any theme name from https://bootswatch.com
      COLOR: "dark"                     # optional
